### ISSUE TITLE
Request: Please have all options disabled by default.

### ISSUE THREAD

**Issue by Thenuclearwalrus** [clanofartisans/ashita-hush#1]
As it comes, it already hushes remote yells.

**Comment by clanofartisans** [comment]
I thought I'd make the default filters a bit opinionated but I think you're right that it's best to leave everything off by default. I've updated the code.

Thanks!

**Commit**: https://github.com/clanofartisans/ashita-hush/commit/acf7d8827affb0357373f1fc532c85de6e0d1d71
