### ISSUE TITLE
HW for Highwind

### ISSUE THREAD

**Issue by bioandroid** [clanofartisans/ashita-hush#5]
Would it be possible to add "HW" as a catchphrase for the highwind filter? Seeing it all the time these days.

Thanks so much for considering, really appreciate the addon!

**Comment by clanofartisans** [comment]
Good idea! I had been thinking about that but forgot :)

Done in version 1.5.1 (https://github.com/clanofartisans/ashita-hush/commit/6d295d217c69a3e87210a1c34a8972d75c6a5494)
